---
working_directory: "/var/www/html/gianyarkab/"
download_directory: "/home/dwik/"
link_website: "https://gianyarkab.com"
host_db: "192.168.1.2"
nama_db: "db_gianyar_kab"
user_db: "root"
password_db: "dwikdwik"
link_github: "https://github.com/cekingx/gianyarkab"
branch_github: "development"
new_user_db: "web"
new_pass_db: "web1234"
