---

  - name: "update apt"
    shell: "apt-get update"
    become: yes

  - name: "install nginx"
    apt: "name=nginx state=latest"

  - name: "buat config load balancer"
    template:
      src: template/loadBalancer.conf.j2
      dest: /etc/nginx/conf.d/loadBalancer.conf
      force: yes

  - name: "restart nginx"
    service:
        name: nginx
        state: restart