---
- hosts: database_server
  become: true
  vars_files:
    - vars/variables.yml

  tasks:
    - name: "Install dan update apt"
      shell: "name={{ item }} state=latest force_apt_get=yes"
      loop:
        - aptitude

    - name: "install mysql"
      apt: "name={{ item }} state=latest"
      loop:
        - mysql-server

    - name: "start services mysql"
      service: "name={{ item }} state=started enabled=yes"
      loop:
        - mysql

    - name: "set root password"
      mysql_user:
        login_host: "localhost"
        login_user: "root"
        login_password: ""
        name: root
        password: "{{ mysql_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Removes all anonymous user accounts
      mysql_user:
        name: ''
        host_all: yes
        state: "absent"
        login_host: "localhost"
        login_user: "root"
        login_password: "{{ mysql_root_password }}"
