---
- hosts: webservers
  become: true
  vars_files:
    - vars/variables.yml

  tasks:
    - name: "Install dan update apt"
      shell: "name={{ item }} state=latest force_apt_get=yes"
      loop:
        - aptitude

    - name: "install apache, mysql, php"
      apt: "name={{ item }} state=latest"
      loop:
        - apache2
        - mysql-server
        - php
        - php-mysql
        - libapache2-mod-php
        - python3-pymysql

    - name: "start services apache mysql"
      service: "name={{ item }} state=started enabled=yes"
      loop:
        - apache2
        - mysql

    - name: "buat document root html"
      file:
        path: "/var/www/{{http_host}}"
        state: directory
        owner: "www-data"
        mode: '0755'

    - name: "konfigurasi virtual host apache"
      template:
        src: "files/apache.conf.j2"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"
      notify: Reload Apache2

    - name: "enable site"
      shell: /usr/sbin/a2ensite {{ http_conf }}
      notify: Reload Apache2

    - name: "disable default site"
      shell: /usr/sbin/a2dissite 000-default.conf
      when: disable_default
      notify: Reload Apache2

    - name: "set root password"
      mysql_user:
        login_host: "localhost"
        login_user: "root"
        login_password: ""
        name: root
        password: "{{ mysql_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Removes all anonymous user accounts
      mysql_user:
        name: ''
        host_all: yes
        state: "absent"
        login_host: "localhost"
        login_user: "root"
        login_password: "{{ mysql_root_password }}"

    - name: "UFW - Allow HTTP on port {{ http_port }}"
      ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp

  handlers:
    - name: Reload Apache2
      service:
        name: apache2
        state: reloaded

    - name: Restart Apache2
      service:
        name: apache2
        state: restarted