---

- hosts: database_server
  become: true
  vars_files:
    - vars/variables.yml

  tasks:
    - name: "php migration"
      shell:
        cmd: "php artisan migrate --force"
        chdir: "{{ working_directory }}"