---

- hosts: database_server
  become: true
  vars_files:
    - vars/variables.yml

  tasks:
    - name: "start services mysql"
      service: "name={{ item }} state=started enabled=yes"
      loop:
        - mysql

    - name: "create new database"
      comunity.mysql.mysql_db:
        login_user: "{{ user_db }}"
        login_password: "{{ password_db }}"
        name: "{{ nama_db }}"
        state: present
    
    - name: "php migration"
      shell:
        cmd: "php artisan migrate --force"
        chdir: "{{ working_directory }}"
    