---
- hosts: webservers
  become: true
  vars_files:
    - vars/variables.yml

  tasks:
    # - name: "download laravel"
    #   get_url:
    #     url: "{{ link_download }}"
    #     dest: "{{ download_directory }}/sistemKoperasi.zip"
    #   register: downloaded_file
    - name: "download laravel project"
      shell:
        cmd: "wget {{ link_download }}"
        chdir: "{{ download_directory }}"

    - name: "extract laravel project"
      unarchive:
        src: "{{ downloaded_file.dest }}"
        dest: "{{ working_directory }}"
        remote_src: yes

    - name: "remove .env"
      file:
        path: "{{ working_directory }}/.env"
        state: absent
    
    - name: "create new .env"
      template:
        src: "template/.env.j2"
        dest: "{{ working_directory }}/.env"

    - name: "php artisan config cache"
      shell:
        cmd: "php artisan config:cache"
        chdir: "{{ working_directory }}"
    
    - name: "php clear the view cache"
      shell:
        cmd: "php artisan view:clear"
        chdir: "{{ working_directory }}"
