---

- hosts: db_server
  become: true
  vars_files:
    - vars/variables.yml

  tasks:
    - name: "start services mysql"
      service: "name={{ item }} state=started enabled=yes"
      loop:
        - mysql

    - name: "create new database"
      community.mysql.mysql_db:
        login_user: "{{ user_db }}"
        login_password: "{{ password_db }}"
        name: "{{ nama_db }}"
        state: present

    - name: "copy sql db to node"
      copy:
        src: "file/db_gianyarkab_new.sql"
        dest: /tmp

    - name: "import database"
      community.mysql.mysql_db:
        name: "{{ nama_db }}"
        state: import
        target: /tmp/db_gianyarkab_new.sql
        login_user: "{{ user_db }}"
        login_password: "{{ password_db }}"

     - name: "buat user untuk diakses web"
       community.mysql.mysql_db:
         state: present
         name: "{{ new_user_db }}"
         password: "{{ new_pass_db }}"
         host: '%'
         priv:
           '{{ nama_db }}.*': 'ALL,GRANT'
         